

PRIMARY_PATA_BASE_ADDRESS0 	equ 	0x1f0
PRIMARY_PATA_BASE_ADDRESS1 	equ 	0x3f0

pio_bmcr_base_addr 	  	equ	0

 PRIMARY_DATA_REGISTER  	equ			PRIMARY_PATA_BASE_ADDRESS0+0
 PRIMARY_ERROR_REGISTER   	equ		     	PRIMARY_PATA_BASE_ADDRESS0+1
 PRIMARY_FEATURE_REGISTER	equ			PRIMARY_PATA_BASE_ADDRESS0+1
 PRIMARY_SECTOR_COUNT_REGISTER  equ			PRIMARY_PATA_BASE_ADDRESS0+2
 PRIMARY_SECTOR_NUMBER_REGISTER equ			PRIMARY_PATA_BASE_ADDRESS0+3
 PRIMARY_CYLINDER_LOW_REGISTER  equ			PRIMARY_PATA_BASE_ADDRESS0+4
 PRIMARY_CYLINDER_HIGH_REGISTER equ			PRIMARY_PATA_BASE_ADDRESS0+5
 PRIMARY_DEVICE_HEAD_REGISTER   equ			PRIMARY_PATA_BASE_ADDRESS0+6
 PRIMARY_PRIMARY_STATUS_REGISTER equ			PRIMARY_PATA_BASE_ADDRESS0+7
 PRIMARY_COMMAND_REGISTER   	 equ			PRIMARY_PATA_BASE_ADDRESS0+7
 PRIMARY_ALTERNATE_STATUS_REGISTER  equ			PRIMARY_PATA_BASE_ADDRESS1+6
 PRIMARY_DEVICE_CONTROL_REGISTER    equ			PRIMARY_PATA_BASE_ADDRESS1+6
 PRIMARY_DEVICE_ADDRESS_REGISTER    equ			PRIMARY_PATA_BASE_ADDRESS1+7


; device control  bits

DEVICE_CONTROL_HIGH_ORDER_BYTE	    	EQU	0x80  ; High Order Byte (48-bit LBA)
DEVICE_CONTROL_HD15   			EQU	0x00  ; bit 3 is reserved
DEVICE_CONTROL_SOFT_RESET   		EQU	0x04  ; soft reset
DEVICE_CONTROL_DISABLE_INTERRUPTS	EQU	0x02  ; disable interrupts




;%1	target port number
;%2	byte value
%macro	OUTPUT_BYTE	2

   	mov     dx,%1  
   	mov     al,%2
   	out     dx,al
	
%endmacro


;%1 source port
;result is in al
%macro	INPUT_BYTE	1
	   mov	   dx,%1
	   in      al,dx	
%endmacro 





%macro	DELAY_100NS	0
	INPUT_BYTE(PRIMARY_ALTERNATE_STATUS_REGISTER)
%endmacro



%macro	DELAY400NS	0

	DELAY_100NS
        DELAY_100NS
        DELAY_100NS
        DELAY_100NS

%endmacro

global	_resetPrimaryDevice0
_resetPrimaryDevice0:

	pushad
	
	OUTPUT_BYTE PRIMARY_DEVICE_CONTROL_REGISTER,(DEVICE_CONTROL_HD15 | DEVICE_CONTROL_DISABLE_INTERRUPTS | DEVICE_CONTROL_SOFT_RESET)

	;now  a deplay for 400  NS
   	DELAY400NS

        OUTPUT_BYTE PRIMARY_DEVICE_CONTROL_REGISTER,(DEVICE_CONTROL_HD15 | DEVICE_CONTROL_DISABLE_INTERRUPTS)

	mov	cx,25000
delay_loop:
   	DELAY400NS;

	loop	delay_loop
	
	popad

	ret
